### PR TITLE
Added russian translation to strings.json :p

### PR DESCRIPTION
**Pull request by vladciphersky**
Amm, hey, I opened this PR. Can you check and merge it?

### CODE REVIEW

**Comment by pedrofracassi** [comment]
Also please be aware that these won't work right away due to #14. But it's good to have the translation ready for when we fix it :)

**Comment by vladciphersky** [comment]
@pedrofracassi Hmm, sorry for the offtopic, but it seems you also have something broken
image

**Comment by pedrofracassi** [comment]
> @pedrofracassi Hmm, sorry for the offtopic, but it seems you also have something broken

Yeah, something seems to be broken on our side. I'll get it fixed.

In the meantime, please pull the latest changes to your fork. I've pushed a change that should get that Lint action to pass.

**Comment by pedrofracassi** [comment]
There we go. The 502 error you were getting should be fixed now.

**Comment by pedrofracassi** [comment]
Hey, please make sure that the strings follow our [string guidelines](https://github.com/SwitchbladeBot/invidget#string-guidelines). The ones you've added don't seem to match the ones on the client: 

image

**Comment by vladciphersky** [comment]
image

**Comment by pedrofracassi** [comment]
Well, I guess mine are different them :p

Thanks for your Pull Request!

**Comment by vladciphersky** [comment]
@pedrofracassi If you send an invite, Discord will show you "Вы отправили приглашение" (You have sent an invitation), so "Вы были приглашены присоединиться к серверу" (You have been invited to join a server) is correct here

**Comment by pedrofracassi** [comment]
Oh, ok

**Comment by vladciphersky** [comment]
Also check this commit: https://github.com/vladciphersky/invidget/commit/dc0b9eff8fe77f384cd0650d9b49062c72a840e6

**Comment by pedrofracassi** [comment]
Yup, I've fixed that on the master branch. Thanks!

**Pull request merged**
